### PR TITLE
Support both nicks and channels

### PR DESCRIPTION
**Pull request by imbstack**
This is pretty much just what @eskil did in 2011 but with an option so that it is compatible with the previous interface.

### CODE REVIEW

**Comment by imbstack** [comment]
This is the fastest review feedback I've ever received. Let alone on a project that hasn't been touched in 2 years. Give me a sec to make that change.

**Comment by thwarted** [comment]
Yes, but how is the quality of the feedback?

I like to think that a project not being touched in a while means it's stable, satisfies its purposes, and has no known bugs.

**Comment by thwarted** [comment]
I don't currently have an IRC server available to do tests against. Please test the following cases

```
nodebot dachan "sent to a channel named dachan"
nodebot --user dachan "sent to a user named dachan"
nodebot '#dauser' "error, noop, or sent to a channel named dauser"
nodebot --user '#dauser' "error, noop, or sent to a user named dauser"
```

For the last two, I'm fine with it either erroring out/not sending a message.  That is, the actual destination of the message is based on if `--user` is specified, not on if the target includes a leading hash.

**Comment by imbstack** [comment]
Quality of the feedback is high! I also like stable projects that don't need to be updated frequently.

@hashbrowncipher and I have looked this over and we think the logic is correct in the current implementation. It won't add a second hash because line 584 is actually the one that is adding the hash in the first place.

We've tested the script in all four of the cases you mention and it does the correct thing in each case. The second two throw an error because the "channel" argument is not allowed to contain a hash. We also tested it with a channel with a hash in the name (which apparently is valid) and it works in that case as well.

**Comment by thwarted** [comment]
Let's say it does an "acceptable" thing in the last two cases, rather than "correct". :smile:

> The second two throw an error because the "channel" argument is not allowed to contain a hash.

I don't see where this is being enforced now, since the regular expression that matches the message destination in the dependent process explicitly allows hashes in the channel name.

> We also tested it with a channel with a hash in the name (which apparently is valid) and it works in that case as well.

What does "works" mean in this context?  That it does one of the acceptable things or that the message is sent to the channel with a hash in the name?  This also doesn't jive with the above because the case can not be both that a channel can not contain a hash and that it successfully sent a message to a destination (channel or user) with a hash in the name or nick.

This looks good otherwise, I just want to make sure we're being explicit about the intent here.

**Comment by imbstack** [comment]
Ok, yeah. Disregard what I was saying about the latter two cases. I left a previous daemon running and was actually using that one.

In a sense the `-u` flag is a misnomer seeing as how it allows you to send to a channel if you just prepend a hash to the destination. Perhaps we could change the name to be `--dont-force-channel` or something of the sort.

If we do that and have a check that says the channel doesn't begin with a hash when the new flag isn't specified makes it behave the same way as previously except with new functionality, right?

**Comment by thwarted** [comment]
So part of the reason that the original version only took channel names sans hash was because I didn't want to require quoting the channel argument, since `#` is a shell meta (despite that liberal quoting in shell is a prudent thing).

However, the original version required the hash in the communication between the primary and dependent processes for channels, despite that only channels could be sent messages.  This is good because that interface follows IRC nick/channel naming conventions already, and we're only talking here about the user-facing interface given on the command line.

Let's fix up the user-facing interface to be more like what you'd expect for IRC.  Nicks are bare and channels are specified with leading hashes.  But remain backwards compatible too.

Define a new boolean option in the config file `[DEFAULT]` section (I'm fine with it being global and not overrideable on a per-identity basis) named `explicit-message-recipients`).

If `explicit-message-recipients` is **not** specified or has the value `False`, the interpretation of the channel argument is as it is now: the name given on the command line is assumed to be a channel name and will have a hash blindly prepended to it

If `explicit-message-recipients` is `True`, then the `<channel>` argument is passed through to the primary process unadorned and its interpretation is how the IRC server would interpret it with a leading hash or not.

In either case, I think it would be valuable to sanity check the value of `channel` (`argv.pop(0)`) around line 561 in `become_dependent` to make sure it is only composed of legal channel/nick characters, conservatively defined as `^[\w-]+$` for `explicit-message-recipients == False` and `^#?[\w-]+$` for `explicit-message-recipients == True`.  Let's not go overboard on allowing any ol' willy-nilly thing (like infix hashes or full-utf8 that doesn't match `\w` — those should be rare enough to not warrant complicating the sanity check).

Also, change the included `nodebot.conf` to have `explicit-message-recipients=True` and we'll consider that to be the new, default interface.

**Comment by imbstack** [comment]
The only problem with changing the default based on the config is that (as I understand it) this will mean that all invocations of nodebot in different projects will need to be upgraded in lock-step with the upgrade of nodebot. Having a user facing  option allows a slow move to the new version across all of the invocations across our organization.

**Comment by thwarted** [comment]
You know, I thought of that, then there was a delay when I started typing it up, and I had forgotten.

What I originally was thinking was that the option would be tri-state.
- If `explicit-message-recipients` is not specified, it uses the current semantics, where you can only send to channels.  The channel name argument is unadorned, but is prefixed with a hash when given to the primary process.
- `explicit-message-recipients=argument`, then the channel argument indicates a channel, unless `--user` is given in which case it is a nick (as in your original commit).  The channel name argument is unadorned, and is conditionally prefixed with a hash when given to the primary process.
- `explicit-message-recipients=bareisnick`, then the channel argument indicates a channel if it is prefixed with a hash and a nick if it is bare.  The channel name argument is passed through to the primary process as is.  The `--user` argument, if given, is ignored.

In all cases, the channel argument should be validated against `^#?[\w-]+$` and rejected if it doesn't match.

The default config file should include `explicit-message-recipients=bareisnick` so new installs are encouraged to use the commonly understood IRC meanings of message recipient designations.

This lets you acquire the new feature in a backwards compatible and more controlled way and we migrate to the more common understanding of how message recipients are specified.

**Comment by imbstack** [comment]
Ok, that seems like a reasonable option. I'm out of time to work on this though. We can just leave the PR and comments here sitting around for a future person who wants to work on this. Feel free to close this if you want.

**Pull request closed without merging**
